### ISSUE TITLE
test_stream.py error with Channels 4

### ISSUE THREAD

**Issue by paolodina** [fanout/django-eventstream#100]
```python
$ python tests/test_stream.py 
Traceback (most recent call last):
  File "/tmp/django-eventstream/tests/test_stream.py", line 6, in <module>
    from django_eventstream.consumers import EventsConsumer, Listener
  File "/tmp/django-eventstream/.venv/lib/python3.10/site-packages/django_eventstream/__init__.py", line 17, in <module>
    from . import routing
  File "/tmp/django-eventstream/.venv/lib/python3.10/site-packages/django_eventstream/routing.py", line 2, in <module>
    from . import consumers
  File "/tmp/django-eventstream/.venv/lib/python3.10/site-packages/django_eventstream/consumers.py", line 7, in <module>
    from channels.http import AsgiRequest
ModuleNotFoundError: No module named 'channels.http'
```

Everything fine downgrading Channels to v3.0.5.

https://channels.readthedocs.io/en/latest/releases/4.0.0.html

**Comment by jkarneges** [comment]
It looks like this has to do with the removal of `AsgiRequest` which happened [here](https://github.com/django/channels/commit/9c1ac42f2a5b4dbfcdade02bd52445bab2851cb9).

Django doesn't offer the same class so I'm not sure what we're supposed to switch to. Maybe the standard request/response objects. I've asked the maintainer.

If it turns out we should switch to standard Django objects, then that'd be pretty exciting since we've been waiting years to be able to do that. But porting the code won't be simple, so users should stick to channels 3 until this can be investigated.

**Comment by paolodina** [comment]
Thanks for the clear answer. Sounds intriguing, please keep us informed.

**Comment by jpmateo022** [comment]
I reverted to 3.0.5 to make it work. Will wait for the new version.

**Comment by markandrewj** [comment]
I had this same issue using channels 4 with Django 4.

**Comment by gagamil** [comment]
Ran into the same issue. The details are [here](https://channels.readthedocs.io/en/stable/releases/4.0.0.html#decoupling-of-the-daphne-application-server).

My solution was to use the previous _channels_ version which is 3.0.5

**Comment by dpgraham4401** [comment]
subscribing

**Comment by dpgraham4401** [comment]
Just following the what ya'll mentioned and the [channels 4.0.0 release notes](https://channels.readthedocs.io/en/latest/releases/4.0.0.html) I replaced the `ASGIRequest` from `channels.http` with `django.core.handlers.asgi.ASGIRequest` in a POC branch here https://github.com/dpgraham4401/django-eventstream/tree/channels_4_support_POC

I've been able install the django-eventstream package locally with `pip install -e` and make it through the django-eventstream geting started guide using channels version 4.0.0.

**Comment by ellethee** [comment]
> It looks like it's possible to replace [`ASGIRequest`](https://github.com/django/channels/blob/76fddba32b3abdfeb390e219e3fbf11f282c95cc/channels/http.py#L24) from `channels.http` with [`django.core.handlers.asgi.ASGIRequest`](https://github.com/django/django/blob/2584783f46922bcb456ceb9700a3726314df65d3/django/core/handlers/asgi.py#L38) 

I adopted the same solution and it seems to work.

**Comment by jkarneges** [comment]
> It looks like it's possible to replace [`AsgiRequest`](https://github.com/django/channels/blob/76fddba32b3abdfeb390e219e3fbf11f282c95cc/channels/http.py#L24) from `channels.http` with [`django.core.handlers.asgi.ASGIRequest`](https://github.com/django/django/blob/2584783f46922bcb456ceb9700a3726314df65d3/django/core/handlers/asgi.py#L38)

[edited case in quote]

Great find @dpgraham4401! It appears `ASGIRequest` has been available in Django for a while, forked from the original in Channels. Maybe I missed it due to the case change.

Simply switching to the new class doesn't work for me though, at least with django-eventstream's chat demo. Connections are immediately disconnected and the browser reconnects over and over. I'll do more investigation.

**Comment by jkarneges** [comment]
Ok! I've ported the code to use `StreamingHttpResponse` instead of channels. Apparently it has been async capable since Django 4.2. However it wasn't until 5.0 that it could handle disconnections properly.

Since it's a pretty big change, can anyone else try it out before I publish a new version?

**Comment by paolodina** [comment]
Hi @jkarneges, unfortunately, I don't have access to the application to test it with this fix. FWIW, I tested the examples in a codespace and they worked great. I also had a look at the diff, and in my limited experience, it looks good. Thanks for taking the time to work on this.
